package com.takaichi00.domain.symphogear;

public enum SymphogearModeStatus {
  NORMAL,
  LAST_BATTLE,
  CHANCE_GX_BEFORE_ALLOCATION,
  CHANCE_GX_4R_11ROTATION,
  CHANCE_GX_10R_11ROTATION,
  CHANCE_GX_10R_103ROTATION,
  CHANCE_GX_10R_15ROTATION,
  CHANCE_GX_6R_11ROTATION,
  CHANCE_GX_7R_11ROTATION
}
